export default {
    START_GAME: 'START_GAME',
    RESET_GAME: 'RESET_GAME',
    END_GAME: 'END_GAME',

    RESET_SCOREBOARD: 'RESET_SCOREBOARD',

    PLACE_TILE: 'PLACE_TILE',

    VERIFY_WIN: 'VERIFY_WIN',
    VERIFY_TIE: 'VERIFY_TIE',

    CHANGE_GAMESTATE: 'CHANGE_GAMESTATE'
}