export default {
    START_GAME: 'START_GAME',
    RESET_GAME: 'RESET_GAME',
    END_GAME: 'END_GAME',

    RESET_SCOREBOARD: 'RESET_SCOREBOARD',
    UPDATE_PVP_SCOREBOARD: 'UPDATE_PVP_SCOREBOARD',
    UPDATE_PVE_SCOREBOARD: 'UPDATE_PVE_SCOREBOARD',

    PLACE_TILE: 'PLACE_TILE',

    VERIFY_WIN: 'VERIFY_WIN',
    VERIFY_TIE: 'VERIFY_TIE',
    
    CHANGE_TURN: 'CHANGE_TURN',

    CHANGE_GAMESTATE: 'CHANGE_GAMESTATE',
    CHANGE_TYPE: 'CHANGE_TYPE',

    RESET_STATE: 'RESET_STATE',

    CHANGE_DIFFICULTY: 'CHANGE_DIFFICULTY'
}